#PLAY LEVEL VARIABLES
- name: variables to print
  hosts: web
  tasks:
  - name: print the information
    ansible.builtin.debug:
      msg: "Hi, I,m learning Devops with AWS, Duration: 120Hrs, Trainer: siva"