- name: variables from prompt
  hosts: web
  vars_prompt:
  - name: COURSE
    prompt: please enter the course name
  - name: Trainer
    prompt: please enter the trainer name
  - name: DURATION
    prompt: please enter the Duration
  tasks:
  - name: print the course info
    ansible.builtin.debug:
      msg: "Hi, I'm learning {{COURSE}}, Duration: {{DURATION}}, Trainer: {{Trainer}}"