- name: create user
  hosts: web
  become: yes
  tasks:
  - name: check the user exist or not
    ansible.builtin.command: id expense
    register: USER #here USER is a variable that gets output from above command
    ignore_errors: True


  - name: print the user information
    ansible.buitin.debug:
      msg: "user info: {{ USER }}"

  # - name: create user
